In [34]:
import pandas as pd

In [36]:
csv_file = 'data/blkjckhands.csv'
df = pd.read_csv(csv_file)
df

,Unnamed: 0,PlayerNo,card1,card2,card3,card4,card5,sumofcards,dealcard1,dealcard2,...,dealcard4,dealcard5,sumofdeal,blkjck,winloss,plybustbeat,dlbustbeat,plwinamt,dlwinamt,ply2cardsum
0,0,Player1,7,10,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
1,1,Player2,10,9,0,0,0,19,10,8,...,0,0,18,nowin,Win,Plwin,Beat,20,0,19
2,2,Player3,9,8,0,0,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,17
3,3,Player4,2,10,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
4,4,Player5,10,2,0,5,0,17,10,8,...,0,0,18,nowin,Loss,Beat,Dlwin,0,10,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899995,1,Player2,10,7,0,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,17
899996,2,Player3,6,1,10,0,0,17,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,7
899997,3,Player4,4,2,9,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,6
899998,4,Player5,9,10,0,0,0,19,3,9,...,2,0,18,nowin,Win,Plwin,Beat,20,0,19
899999,5,Player6,5,10,0,0,0,15,3,9,...,2,0,18,nowin,Loss,Beat,Dlwin,0,10,15

In [38]:
df.columns

Index(['Unnamed: 0', 'PlayerNo', 'card1', 'card2', 'card3', 'card4', 'card5',
       'sumofcards', 'dealcard1', 'dealcard2', 'dealcard3', 'dealcard4',
       'dealcard5', 'sumofdeal', 'blkjck', 'winloss', 'plybustbeat',
       'dlbustbeat', 'plwinamt', 'dlwinamt', 'ply2cardsum'],
      dtype='object')

In [40]:
csv_file_m = 'data/blackjack_simulator.csv'
df_m = pd.read_csv(csv_file_m)
df_m

,shoe_id,cards_remaining,dealer_up,initial_hand,dealer_final,dealer_final_value,player_final,player_final_value,actions_taken,run_count,true_count,win
0,0,416,10,"[10, 11]","[10, 4, 10]",24,"[[10, 11]]",['BJ'],[['S']],1,0,1.5
1,0,411,10,"[5, 5]","[10, 8]",18,"[[5, 5, 11]]",[21],"[['H', 'S']]",-2,0,1.0
2,0,406,6,"[3, 10]","[6, 6, 10]",22,"[[3, 10]]",[13],[['S']],-2,0,1.0
3,0,401,10,"[5, 9]","[10, 8]",18,"[[5, 9, 11, 3]]",[18],"[['H', 'H', 'S']]",-1,0,0.0
4,0,395,8,"[6, 10]","[8, 2, 10]",20,"[[6, 10, 10]]",[26],[['H']],-1,0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49999995,822844,108,10,"[7, 9]","[10, 3, 10]",23,"[[7, 9]]",[16],[['R']],14,6,-0.5
49999996,822844,103,5,"[9, 9]","[5, 2, 5, 9]",21,"[[9, 10], [9, 10]]","[19, 19]","[['P', 'S'], ['S']]",13,6,-2.0
49999997,822844,95,10,"[10, 10]","[10, 10]",20,"[[10, 10]]",[20],[['S']],14,7,0.0
49999998,822844,91,9,"[4, 10]","[9, 10]",19,"[[4, 10, 9]]",[23],[['H']],10,5,-1.0
49999999,822844,86,10,"[10, 8]","[10, 10]",20,"[[10, 8]]",[18],[['S']],9,5,-1.0

In [42]:
df_m.columns

Index(['shoe_id', 'cards_remaining', 'dealer_up', 'initial_hand',
       'dealer_final', 'dealer_final_value', 'player_final',
       'player_final_value', 'actions_taken', 'run_count', 'true_count',
       'win'],
      dtype='object')